/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_dynamodb_all_tables_region": "eu-west-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "contact-dev",
            "region": "eu-west-2"
        },
        {
            "tableName": "stats-dev",
            "region": "eu-west-2"
        },
        {
            "tableName": "entities-dev",
            "region": "eu-west-2"
        },
        {
            "tableName": "project-dev",
            "region": "eu-west-2"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://je6j6hivvfhwvmcpmy7qurqxva.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "AWS_IAM",
    "aws_content_delivery_bucket": "wprn-frontend-dev-dev",
    "aws_content_delivery_bucket_region": "eu-west-2",
    "aws_content_delivery_url": "http://wprn-frontend-dev-dev.s3-website.eu-west-2.amazonaws.com",
    "aws_cognito_identity_pool_id": "eu-west-2:da0d71ea-0a24-4fea-b58f-65603bc53313",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_CN10qwDFx",
    "aws_user_pools_web_client_id": "65p357o424tacluk9ik6ho9e1u",
    "oauth": {}
};


export default awsmobile;
