query list (
  $filter: ModelProjectFilterInput
  $limit: Int
  $nextToken: String)
  {
  listProjects (filter: $filter, limit: $limit, nextToken: $nextToken){
    items {
      id
      name
      description
      status
      type
      field
      url
      contact_firstname
      contact_lastname
      contact_entity
      zone
      country
      city
      date
      time
      createdAt
      views
    }
    nextToken
  }
}
